### PR TITLE
remove container after extraction

### LINKED ISSUE #8: Failing to cleanup target container when an error occurs
It seems that if an error occurs [between the target container creation and its removal](https://github.com/simon3z/image-inspector/blob/3f0f8dd05d0c0a3651a760a84979c3ef75289348/image-inspector.go#L242-L290) such container is not removed leaving the environment dirty.

We should create a cleanup function that attempts to remove the target container to call in such cases.

cc @pweil- @enoodle (can anyone of you take this?)

### PR DESCRIPTION
**Pull request by pweil-**
Fixes https://github.com/simon3z/image-inspector/issues/8

After a second look I realized we can do this with a single defer if I extracted a method which is probably better anyway.  

@simon3z @enoodle PTAL

Build and test:

```
[pweil@localhost image-inspector]$ rm image-inspector
[pweil@localhost image-inspector]$ go build cmd/image-inspector.go 
[pweil@localhost image-inspector]$ ./image-inspector --image=fedora:22 --serve 0.0.0.0:8080
2016/04/11 10:43:47 Image fedora:22 is available, skipping image pull
2016/04/11 10:43:47 Extracting image fedora:22 to /var/tmp/image-inspector-283317876
2016/04/11 10:43:49 !!!WARNING!!! It is insecure to serve the image content without changing
2016/04/11 10:43:49 root (--chroot). Absolute-path symlinks in the image can lead to disclose
2016/04/11 10:43:49 information of the hosting system.
2016/04/11 10:43:49 Serving image content /var/tmp/image-inspector-283317876 on webdav://0.0.0.0:8080/api/v1/content/
[pweil@localhost image-inspector]$ go test -v -cover ./...
?       github.com/simon3z/image-inspector/cmd  [no test files]
=== RUN   TestValidate
--- PASS: TestValidate (0.00s)
PASS
coverage: 75.0% of statements
ok      github.com/simon3z/image-inspector/pkg/cmd  0.001s  coverage: 75.0% of statements
?       github.com/simon3z/image-inspector/pkg/inspector    [no test files]
[pweil@localhost image-inspector]$ 
```

### CODE REVIEW

File: pkg/inspector/image-inspector.go [hunk 1]
```diff
@@ -195,6 +145,73 @@ func (i *defaultImageInspector) Inspect() error {
...
+	} else {
+		// forcing to use /var/tmp because often it's not an in-memory tmpfs
+		i.opts.DstPath, err = ioutil.TempDir("/var/tmp", "image-inspector-")
+		if err != nil {
+			return imageMetadata, fmt.Errorf("Unable to create temporary path: %v\n", err)
+		}
+	}
+
+	reader, writer := io.Pipe()
+	go handleTarStream(reader, i.opts.DstPath)
```
Comment (enoodle) [inline pkg/inspector/image-inspector.go]: @pweil-, @simon3z  what if `handleTarStream` is taking more time for some reason but `createAndExtractImage` gets to its end? `handleTarStream` will keep working but maybe if it is slow we will get to the scanning with some of the files not written yet. Should we add some kind of channel here and wait for `handleTarStream` to finish? This existed before this patch and is not connected to it, but I noticed this now.

**Comment by enoodle** [comment]
LGTM :+1:

File: pkg/inspector/image-inspector.go (hunk 1 above)
Comment (pweil-) [inline pkg/inspector/image-inspector.go]: I was wondering that too.  We could throw a channel in there like you suggest and wait on the channel or a timeout.

Comment (simon3z) [inline pkg/inspector/image-inspector.go]: @enoodle @pweil- I'll probably need to see it in code. Can you re-submit with that change as well (in a different patch so it's easier to add/remove) thanks.

File: pkg/inspector/image-inspector.go [hunk 2]
```diff
@@ -197,7 +198,8 @@ func (i *defaultImageInspector) createAndExtractImage(client *docker.Client, con
 	}
 
 	reader, writer := io.Pipe()
-	go handleTarStream(reader, i.opts.DstPath)
+	notificationChannel := make(chan int)
+	go handleTarStream(reader, i.opts.DstPath, notificationChannel)
```
Comment (pweil-) [inline pkg/inspector/image-inspector.go]: @simon3z @enoodle adds a notification channel to the async method

File: pkg/inspector/image-inspector.go [hunk 3]
```diff
@@ -197,7 +198,8 @@ func (i *defaultImageInspector) createAndExtractImage(client *docker.Client, con
...
 
 	log.Printf("Extracting image %s to %s", i.opts.Image, i.opts.DstPath)
 	err = client.CopyFromContainer(docker.CopyFromContainerOptions{
```
Comment (pweil-) [inline pkg/inspector/image-inspector.go]: important to note here that since this is a synchronous call we are blocking for the duration of the copy.  So really the only place a timeout would occur is if there is logic in `handleTarStream` or `processTarStream` that executes after this returns

File: pkg/inspector/image-inspector.go [hunk 4]
```diff
@@ -223,6 +231,7 @@ func handleTarStream(reader io.ReadCloser, destination string) {
 		log.Printf("Unable to create image tar reader")
 	}
 	reader.Close()
```
Comment (pweil-) [inline pkg/inspector/image-inspector.go]: ie. if I put a sleep here we'd see the select above return an error

**Comment by simon3z** [comment]
@pweil- we may need to queue this behind #3

**Comment by simon3z** [comment]
@pweil- let's try to merge this next. (It needs to be rebased).

**Comment by pweil-** [comment]
rebased.  @enoodle can you double check the merge here to make sure I didn't miss anything?  Thanks!

tests:

```
[pweil@localhost image-inspector]$ go test -cover ./...
?       github.com/simon3z/image-inspector/cmd  [no test files]
ok      github.com/simon3z/image-inspector/pkg/cmd  0.002s  coverage: 100.0% of statements
ok      github.com/simon3z/image-inspector/pkg/inspector    0.002s  coverage: 10.5% of statements
ok      github.com/simon3z/image-inspector/pkg/openscap 0.004s  coverage: 38.3% of statements
```

**Comment by simon3z** [comment]
@enoodle please re-review.

**Comment by enoodle** [comment]
LGTM :+1:

File: pkg/inspector/image-inspector.go [hunk 5]
```diff
@@ -221,7 +183,70 @@ func (i *defaultImageInspector) Inspect() error {
...
+	})
+	if err != nil {
+		return imageMetadata, fmt.Errorf("Unable to extract container: %v\n", err)
+	}
+
+	select {
+	case <-notificationChannel:
+		break
+	case <-time.After(time.Minute * 2):
+		return imageMetadata, fmt.Errorf("timeout occured waiting for handleTarStream to finish")
```
Comment (simon3z) [inline pkg/inspector/image-inspector.go]: @pweil- I am really worried about this one. IIUC if the extraction is longer than 2 minutes then we exit. It would be better if it was "2 minutes of inactivity"... but as it is now worries me.

Any chance that we can remove it? Maybe we can make it configurable... but I am worried anyway.

Comment (pweil-) [inline pkg/inspector/image-inspector.go]: Why don't we just not use a separate go routine when calling `handleTarStream`?  Then all this goes away.

Comment (pweil-) [inline pkg/inspector/image-inspector.go]: never mind, that is required for the copy to start.  Ok, let me look at it

Comment (simon3z) [inline pkg/inspector/image-inspector.go]: @pweil- yeah I am all to remove the go routine if possible.

**Comment by pweil-** [comment]
Refactored the second commit so it will wait until both `handleTarStream` and the `CopyFromContainer` are finished without using a timeout.  We can add a reasonable timeout later if necessary.

Testing:

```
# build
[pweil@localhost image-inspector]$ go build cmd/image-inspector.go 

# unit tests
[pweil@localhost image-inspector]$ go test -cover ./...
?       github.com/simon3z/image-inspector/cmd  [no test files]
ok      github.com/simon3z/image-inspector/pkg/cmd  0.002s  coverage: 100.0% of statements
ok      github.com/simon3z/image-inspector/pkg/inspector    0.002s  coverage: 10.6% of statements
ok      github.com/simon3z/image-inspector/pkg/openscap 0.003s  coverage: 38.3% of statements

# end-to-end
[pweil@localhost image-inspector]$ ./image-inspector --image=fedora:22 --serve 0.0.0.0:8080
2016/04/20 11:24:41 Image fedora:22 is available, skipping image pull
2016/04/20 11:24:41 Extracting image fedora:22 to /var/tmp/image-inspector-260853666
2016/04/20 11:24:43 !!!WARNING!!! It is insecure to serve the image content without changing
2016/04/20 11:24:43 root (--chroot). Absolute-path symlinks in the image can lead to disclose
2016/04/20 11:24:43 information of the hosting system.
2016/04/20 11:24:43 Serving image content /var/tmp/image-inspector-260853666 on webdav://0.0.0.0:8080/api/v1/content/
^C

# make sure it was extracted still
[pweil@localhost image-inspector]$ ll /var/tmp/image-inspector-260853666
total 80
drwxr-xr-x. 18 pweil pweil  4096 Apr 20 11:24 .
drwxrwxrwt. 47 root  root  12288 Apr 20 11:24 ..
lrwxrwxrwx.  1 pweil pweil     7 Apr 20 11:24 bin -> usr/bin
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 boot
drwxr-xr-x.  4 pweil pweil  4096 Apr 20 11:24 dev
-rwxr-xr-x.  1 pweil pweil     0 Apr 20 11:24 .dockerenv
-rwxr-xr-x.  1 pweil pweil     0 Apr 20 11:24 .dockerinit
drwxr-xr-x. 46 pweil pweil  4096 Apr 20 11:24 etc
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 home
lrwxrwxrwx.  1 pweil pweil     7 Apr 20 11:24 lib -> usr/lib
lrwxrwxrwx.  1 pweil pweil     9 Apr 20 11:24 lib64 -> usr/lib64
drwx------.  2 pweil pweil  4096 Apr 20 11:24 lost+found
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 media
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 mnt
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 opt
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 proc
drwxr-x---.  2 pweil pweil  4096 Apr 20 11:24 root
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 run
lrwxrwxrwx.  1 pweil pweil     8 Apr 20 11:24 sbin -> usr/sbin
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 srv
drwxr-xr-x.  2 pweil pweil  4096 Apr 20 11:24 sys
drwxrwxr-t.  7 pweil pweil  4096 Apr 20 11:24 tmp
drwxr-xr-x. 12 pweil pweil  4096 Apr 20 11:24 usr
drwxr-xr-x. 18 pweil pweil  4096 Apr 20 11:24 var
```

**Comment by simon3z** [comment]
@enoodle please review ASAP. Thanks!

File: pkg/inspector/image-inspector.go [hunk 6]
```diff
@@ -221,6 +182,78 @@ func (i *defaultImageInspector) Inspect() error {
...
+		})
+	}()
+
+	// block on handling the reads here so we ensure both the write and the reader are finished
+	// (read waits until an EOF or error occurs).
+	handleTarStream(reader, i.opts.DstPath)
+
+	// capture any error from the copy, ensures both the handleTarStream and CopyFromContainer
+	// are done.
+	err = <- errorChannel
```
Comment (enoodle) [inline pkg/inspector/image-inspector.go]: nit: gofmt is angry at this space after the arrow

Comment (pweil-) [inline pkg/inspector/image-inspector.go]: fixed

File: pkg/inspector/image-inspector.go [hunk 7]
```diff
@@ -221,6 +182,78 @@ func (i *defaultImageInspector) Inspect() error {
...
+		return imageMetadata, fmt.Errorf("Unable to get docker image information: %v\n", err)
+	}
+
+	if i.opts.DstPath, err = createOutputDir(i.opts.DstPath, "image-inspector-"); err != nil {
+		return imageMetadata, err
+	}
+
+	reader, writer := io.Pipe()
+	// handle closing the reader/writer in the method that creates them
+	defer writer.Close()
```
Comment (enoodle) [inline pkg/inspector/image-inspector.go:227]: @pweil- we didn't have anything to close `writer` before?

Comment (pweil-) [inline pkg/inspector/image-inspector.go:227]: no, didn't see anything

Comment (pweil-) [inline pkg/inspector/image-inspector.go:227]: (I also checked if CopyFromContainer was doing it but it wasn't)

**Comment by enoodle** [comment]
@simon3z @pweil- LGTM :+1:

File: pkg/inspector/image-inspector.go (hunk 7 above)
Comment (enoodle) [inline pkg/inspector/image-inspector.go:227]: then we got evene better than we aimed for :) :cake:
